# Deploy the Bot in digitalocean on every PUSH

name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: "root"
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/opt/ncell/ncellbot"
   
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: "root"
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: bash /opt/ncell/ncellbot/.github/workflows/deployScript.sh ${{ secrets.CONFIG }}